# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target "IAmHere" do

pod 'AFNetworking', '~> 2.0'
pod 'AFNetworkActivityLogger', '~> 2.0'


end

target "IAmHereTests" do

end

